<h1 align='center' style='color:green'>Credit Risk Modeling Project</h1>

#### Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

##### Load Raw Data

In [8]:
df_customers = pd.read_csv("../DATA/raw/customers.csv")
df_loans = pd.read_csv("../DATA/raw/loans.csv")
df_bureau = pd.read_csv("../DATA/raw/bureau_data.csv")

In [11]:
#how many records do we have
df_customers.shape, df_loans.shape, df_bureau.shape

((50000, 12), (50000, 15), (50000, 8))

In [12]:
df_customers.head(3)

  cust_id  age gender  ...     city        state  zipcode
0  C00001   44      M  ...    Delhi        Delhi   110001
1  C00002   38      M  ...  Chennai   Tamil Nadu   600001
2  C00003   46      F  ...  Kolkata  West Bengal   700001

[3 rows x 12 columns]

In [13]:
df_loans.head(3)

  loan_id cust_id loan_purpose  ... disbursal_date  installment_start_dt  default
0  L00001  C00001         Auto  ...     2019-07-24            2019-08-10    False
1  L00002  C00002         Home  ...     2019-07-24            2019-08-15    False
2  L00003  C00003     Personal  ...     2019-07-24            2019-08-21    False

[3 rows x 15 columns]

In [14]:
df_bureau.head(3)

  cust_id  number_of_open_accounts  ...  enquiry_count  credit_utilization_ratio
0  C00001                        1  ...              3                         7
1  C00002                        3  ...              5                         4
2  C00003                        2  ...              6                        58

[3 rows x 8 columns]

In [20]:
# checking duplicate primary keys before merging

print("Duplicate loan_ids :", df_loans.duplicated("loan_id").sum())

print("Duplicate cust_ids :", df_customers.duplicated("cust_id").sum())

# both datasets are safe for merging

Duplicate loan_ids : 0
Duplicate cust_ids : 0

In [21]:
# taking customer's details on base loan file

df = pd.merge(df_loans, df_customers , on ="cust_id", how ='left')
df.head(2)

  loan_id cust_id loan_purpose  ...     city       state  zipcode
0  L00001  C00001         Auto  ...    Delhi       Delhi   110001
1  L00002  C00002         Home  ...  Chennai  Tamil Nadu   600001

[2 rows x 26 columns]

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_id                      50000 non-null  str
 1   cust_id                      50000 non-null  str
 2   loan_purpose                 50000 non-null  str
 3   loan_type                    50000 non-null  str
 4   sanction_amount              50000 non-null  int64
 5   loan_amount                  50000 non-null  int64
 6   processing_fee               50000 non-null  float64
 7   gst                          50000 non-null  int64
 8   net_disbursement             50000 non-null  int64
 9   loan_tenure_months           50000 non-null  int64
 10  principal_outstanding        50000 non-null  int64
 11  bank_balance_at_application  50000 non-null  int64
 12  disbursal_date               50000 non-null  str
 13  installment_start_dt         50000 non-null  str
 14  default                      50000 non-null  bool
 15  age                          50000 non-null  int64
 16  gender                       50000 non-null  str
 17  marital_status               50000 non-null  str
 18  employment_status            50000 non-null  str
 19  income                       50000 non-null  int64
 20  number_of_dependants         50000 non-null  int64
 21  residence_type               49938 non-null  str
 22  years_at_current_address     50000 non-null  int64
 23  city                         50000 non-null  str
 24  state                        50000 non-null  str
 25  zipcode                      50000 non-null  int64
dtypes: bool(1), float64(1), int64(12), str(12)
memory usage: 9.6 MB

In [26]:
# making output column int
df["default"] = df["default"].astype("int32")
df["default"].dtypes

dtype('int32')

In [ ]:
# checking class imbalanceness

df["default"].value_counts(normalize=True)*100 #1 : defaulter , 0 : non-defauter

default
0    91.406
1     8.594
Name: proportion, dtype: float64

### Train Test Split

In [30]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df,test_size=0.33,random_state=42,stratify=df["default"])

In [31]:
train_df["default"].value_counts(normalize=True)*100 #1 : defaulter , 0 : non-defauter

default
0    91.40597
1     8.59403
Name: proportion, dtype: float64

In [32]:
test_df["default"].value_counts(normalize=True)*100 #1 : defaulter , 0 : non-defauter

default
0    91.406061
1     8.593939
Name: proportion, dtype: float64

In [34]:
# saving splited raw data 
train_df.to_parquet("../DATA/raw/train_df_raw.parquet")
test_df.to_parquet("../DATA/raw/test_df_raw.parquet")